FROM nginx

RUN apt-get -y update \
    && apt-get upgrade -y \
    && apt-get install libfcgi-dev -y \
    && apt-get install gcc -y \
    && apt-get install spawn-fcgi -y \
    && apt-get install curl -y \
    && rm -rf /var/lib/apt/lists

COPY docker-entrypoint.sh /
COPY /server/hello.c /etc/nginx/.
COPY /server/default.conf /etc/nginx/conf.d/default.conf
RUN chmod +x docker-entrypoint.sh

RUN usermod -aG adm,root nginx \
    && chown -R nginx:nginx /var/run/ \
    && chown -R nginx:nginx /var/cache/nginx/ \
    && chown -R nginx:nginx /etc/nginx/

USER nginx

HEALTHCHECK --interval=5m --timeout=3s CMD curl -f http://localhost:80/ || exit 1

ENTRYPOINT [ "/docker-entrypoint.sh" ]
